New matrix workflow template
This new workflow uses the `matrix_from_metadata` script from puppet_litmus
to calculate the required GCP image ids and create an appropriate workflow
matrix.

It also uses updated versions of actions and cleans up the cache.

Note that there is no slack notifications on the PR
workflow as that requires access to secrets that are
not available on workflows running on forks. Given that
PRs also can be very noisy, I don't consider that a big
loss.

diff --git a/.github/workflows/manual_test.yml b/.github/workflows/manual_test.yml
--- a/.github/workflows/manual_test.yml
+++ b/.github/workflows/manual_test.yml
@@ -7,63 +7,135 @@ on:
         description: "URL for the provision service facade"
         required: true
 
+env:
+  HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
+  HONEYCOMB_DATASET: litmus tests
+  SERVICE_URL: ${{ github.event.inputs.service }}/v1/provision
+
 jobs:
-  LitmusAcceptance:
-    runs-on: ubuntu-latest
+  setup_matrix:
+    name: "Setup Test Matrix"
+    runs-on: ubuntu-20.04
+    outputs:
+      matrix: ${{ steps.get-matrix.outputs.matrix }}
     steps:
-    - uses: actions/checkout@v1
-    - name: Set up Ruby 2.7
+    - name: Checkout Source
+      uses: actions/checkout@v2
+
+    - name: Activate Ruby 2.7
       uses: actions/setup-ruby@v1
       with:
-        ruby-version: 2.7
+        ruby-version: "2.7"
+
+    - name: Cache gems
+      uses: actions/cache@v2
+      with:
+        path: vendor/gems
+        key: ${{ runner.os }}-pr-${{ hashFiles('**/Gemfile') }}
+        restore-keys: |
+          ${{ runner.os }}-pr-
+          ${{ runner.os }}-
+
     - name: Install gems
-      run: bundle install
+      run: |
+        bundle config path vendor/gems
+        bundle config jobs 8
+        bundle config retry 3
+        bundle install
+        bundle clean
+
+    - name: Setup Acceptance Test Matrix
+      id: get-matrix
+      run: "bundle exec matrix_from_metadata"
+
+  Acceptance:
+    needs:
+      - setup_matrix
+
+    runs-on: ubuntu-20.04
+    strategy:
+      matrix: ${{fromJson(needs.setup_matrix.outputs.matrix)}}
+
+    steps:
+    - name: Checkout Source
+      uses: actions/checkout@v2
+
+    - name: Activate Ruby 2.7
+      uses: actions/setup-ruby@v1
+      with:
+        ruby-version: "2.7"
+
+    - name: Cache gems
+      uses: actions/cache@v2
+      with:
+        path: vendor/gems
+        key: ${{ runner.os }}-pr-${{ hashFiles('**/Gemfile') }}
+        restore-keys: |
+          ${{ runner.os }}-pr-
+          ${{ runner.os }}-
+
+    - name: Install gems
+      run: |
+        bundle config path vendor/gems
+        bundle config jobs 8
+        bundle config retry 3
+        bundle install
+        bundle clean
+
+    - name: bundler environment
+      run: |
+        bundle env
+
     - name: Provision test environment
       run: |
-        cat <<EOF >> test_machines.json
-        {
-          "url" : "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID",
-          "VMs": [
-            {
-             "cloud": "gcp",
-             "region": "europe-west1",
-             "zone": "europe-west1-d",
-             "images": ["centos-7-v20200618", "windows-server-2016-dc-v20200813"]
-            }
-          ]
-        }
-        EOF
-        curl -X POST ${{ github.event.inputs.service }}/v1/provision --data @test_machines.json > inventory.yaml
-        cat inventory.yaml
+        bundle exec rake 'litmus:provision[provision::provision_service,${{ matrix.platform }}]'
+        echo ::group::=== REQUEST ===
+        cat request.json || true
+        echo
+        echo ::endgroup::
+        echo ::group::=== INVENTORY ===
+        sed -e 's/password: .*/password: "[redacted]"/' < inventory.yaml || true
+        echo ::endgroup::
+
+    # The provision service hands out machines as soon as they're provisioned.
+    # The GCP VMs might still take a while to spool up and configure themselves fully.
+    # This retry loop spins until all agents have been installed successfully.
     - name: Install agent
       uses: nick-invision/retry@v1
       with:
         timeout_minutes: 30
         max_attempts: 5
         retry_wait_seconds: 60
-        command: bundle exec rake 'litmus:install_agent'
+        command: bundle exec rake 'litmus:install_agent[${{ matrix.collection }}]'
+
+    # The agent installer on windows does not finish in time for this to work. To
+    # work around this for now, retry after a minute if installing the module failed.
     - name: Install module
-      run: bundle exec rake 'litmus:install_module'
+      uses: nick-invision/retry@v1
+      with:
+        timeout_minutes: 30
+        max_attempts: 2
+        retry_wait_seconds: 60
+        command: bundle exec rake 'litmus:install_module'
+
     - name: Run acceptance tests
       run: bundle exec rake 'litmus:acceptance:parallel'
+
     - name: Remove test environment
       if: ${{ always() }}
       run: |
-        uniqueid=$(cat inventory.yaml | grep -m 1 uuid | cut -d ':' -f 2 | tr -d ' ')
-        cat <<EOF >> delete_resources.json
-        {
-          "uuid" : "$uniqueid"
-        }
-        EOF
-        echo "Removing uuid"
-        cat delete_resources.json
-        curl -X DELETE ${{ github.event.inputs.service }}/v1/provision --data @delete_resources.json
+        bundle exec rake 'litmus:tear_down'
+        echo ::group::=== REQUEST ===
+        cat request.json || true
+        echo
+        echo ::endgroup::
+
   slack-workflow-status:
     if: always()
     name: Post Workflow Status To Slack
     needs:
-      - LitmusAcceptance
-    runs-on: ubuntu-latest
+      - Acceptance
+    runs-on: ubuntu-20.04
     steps:
       - name: Slack Workflow Notification
         uses: Gamesight/slack-workflow-status@master
